{% set name = "matrix-nio" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matrix_nio-{{ version }}.tar.gz
  sha256: bdba2b4c2fce2009d2ddd32a1a2e7d07bc7f8f3d188328a7fb03b5a01235da86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - aiofiles >=23.1.0,<24.0.0
    - aiohttp >=3.8.3,<4.0.0
    - aiohttp-socks >=0.7.0,<0.8.0
    - h11 >=0.14.0,<0.15.0
    - h2 >=4.0.0,<5.0.0
    - jsonschema >=4.14.0,<5.0.0
    - pycryptodome >=3.10.1,<4.0.0
    - python >=3.8.0,<4.0.0
    - unpaddedbase64 >=2.1.0,<3.0.0
  run_constrained:
    - python-olm >=3.1.3,<4.0.0
    - peewee >=3.14.4,<4.0.0
    - cachetools >=4.2.1,<5.0.0
    - atomicwrites >=1.4.0,<2.0.0

test:
  imports:
    - nio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/matrix-nio
  summary: A Python Matrix client library, designed according to sans I/O principles.
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/poljar/matrix-nio

extra:
  recipe-maintainers:
    - goanpeca
